        InBus   Cost    MaxFreq MaxOnceTime MaxTime MinIntTime
cl1     6       100     2       2           24      0
cl2     7       100     2       2           24      0
cl3     8       100     2       2           24      0
cl4     10      100     2       2           24      0
cl5     11      100     2       2           24      0
cl6     12      100     2       2           24      0
cl7     13      100     2       2           24      0
cl8     14      100     2       2           24      0

